### ISSUE TITLE
Access to x-mockqa-correlation-id from the server side

### ISSUE THREAD

**Issue by derickcassidy** [mockqa/issue-tracker#3]
**Is your feature request related to a problem? Please describe.**
When trying to debug a gRPC payload between a pre-existing server, and mock.qa, there is no way to see the correlation id on the server side to be able to ask for the trace information.  The ability to retrieve the id using the website and then querying the request/response would assist in debugging / testing the service. 

**Describe the solution you'd like**
I'd like to see the correlation id be available for all calls to to the instance in mock.qa portal

**Describe alternatives you've considered**
The ability to view the content of the request / response payloads directly in the portal without the need for cURL would also be acceptable.

**Comment by arxange1** [comment]
Dear @derickcassidy,

We appreciate your inquiry! Your provided context and concern are clear to us. Our team will review the design and implementation specifics, and we will promptly return with an update.

**Comment by arxange1** [comment]
Dear @derickcassidy,

We discussed the problem statement with the team and decided to implement the "Trace Logs" screen. It will provide all requests and their responses for inspection and filtering. We are going to start the development in 24h. It may take up to two weeks including proper testing. We will post an update once the feature is delivered.

Bets regards,
Victor

**Comment by arxange1** [comment]
Dear @derickcassidy,

The feature has been implemented and released to production. It can be accessed using the "Request history" item in the "Tools" menu:

![image](https://user-images.githubusercontent.com/2320016/230193988-8c226f29-478b-40b0-89b5-d7b810d16219.png)

The "Request history" screen:

![image](https://user-images.githubusercontent.com/2320016/230194211-87a323fa-4beb-42c4-ba5e-822f30485464.png)

Rows are clickable. A request modal will be opened once clicked:

![image](https://user-images.githubusercontent.com/2320016/230196056-3a8ac0b6-9971-4c91-8163-972630a2999d.png)

Please note, that the "search" box in the "Request history" screen allows searching a substring in any part of a request and response, You can type several strings separated by space char. Space char is equivalent to OR operator.

It is our first preview release of the feature. Our next step is to enhance the screen with the filter by request time.

We are looking forward for your feedback,

Best regards,
Victor, mock.qa team
